# Generated by Django 3.1.3 on 2020-12-12 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20201212_1458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
